import XLSX from 'xlsx-js-style';
import { InputState } from '../valuation/inputs';
import { computeAnalysis } from '../valuation/engine';

interface PropertyData {
  name: string;
  inputs: InputState;
}

// ── Style constants ──────────────────────────────────────────────────
const FONT_BOLD = { bold: true };
const FONT_HEADER = { bold: true, color: { rgb: 'FFFFFF' }, sz: 11 };
const FONT_SECTION = { bold: true, color: { rgb: '1F4E79' }, sz: 12 };
const FONT_SUBSECTION = { bold: true, color: { rgb: '2E75B6' }, sz: 11 };
const FILL_HEADER = { fgColor: { rgb: '2E75B6' }, patternType: 'solid' } as const;
const FILL_INPUT = { fgColor: { rgb: 'FFF2CC' }, patternType: 'solid' } as const;
const FILL_DERIVED = { fgColor: { rgb: 'E2EFDA' }, patternType: 'solid' } as const;
const FILL_SECTION = { fgColor: { rgb: 'D6E4F0' }, patternType: 'solid' } as const;
const FILL_ALT_ROW = { fgColor: { rgb: 'F2F2F2' }, patternType: 'solid' } as const;
const BORDER_THIN = {
  top: { style: 'thin', color: { rgb: 'B4B4B4' } },
  bottom: { style: 'thin', color: { rgb: 'B4B4B4' } },
  left: { style: 'thin', color: { rgb: 'B4B4B4' } },
  right: { style: 'thin', color: { rgb: 'B4B4B4' } },
} as const;

const FMT_DOLLAR = '#,##0.00';
const FMT_DOLLAR_0 = '#,##0';
const FMT_PCT = '0.00%';
const FMT_INT = '#,##0';

type CellStyle = Record<string, any>;

function cell(v: string | number | boolean | null, s?: CellStyle): Record<string, any> {
  const t = typeof v === 'number' ? 'n' : typeof v === 'boolean' ? 'b' : 's';
  return { v: v ?? '', t, s: { border: BORDER_THIN, ...s } };
}
function hdr(v: string, extra?: CellStyle): Record<string, any> {
  return cell(v, { font: FONT_HEADER, fill: FILL_HEADER, alignment: { horizontal: 'center' }, ...extra });
}
function label(v: string, extra?: CellStyle): Record<string, any> {
  return cell(v, { font: FONT_BOLD, ...extra });
}
function inputCell(v: number, fmt: string): Record<string, any> {
  return cell(v, { fill: FILL_INPUT, numFmt: fmt });
}
function formulaCell(f: string, fmt: string, extra?: CellStyle): Record<string, any> {
  return { t: 'n', f, s: { border: BORDER_THIN, numFmt: fmt, ...extra } };
}
function sectionRow(text: string, cols: number): Record<string, any>[] {
  const row: Record<string, any>[] = [cell(text, { font: FONT_SECTION, fill: FILL_SECTION })];
  for (let i = 1; i < cols; i++) row.push(cell('', { fill: FILL_SECTION }));
  return row;
}

/**
 * Build and download an Excel workbook. Only site inputs are hard values;
 * all analysis numbers are generated by Excel formulas.
 */
export function downloadExcel(properties: PropertyData[]) {
  const wb = XLSX.utils.book_new();

  for (const prop of properties) {
    buildPropertySheet(wb, prop.name, prop.inputs);
  }

  if (properties.length > 1) {
    buildComparisonSheet(wb, properties);
  }

  XLSX.writeFile(wb, 'rental_edge_analysis.xlsx');
}

/* ================================================================== */
/*  Per-property Sheet  (inputs → formulas)                            */
/* ================================================================== */
function buildPropertySheet(wb: XLSX.WorkBook, name: string, inp: InputState) {
  const ws: XLSX.WorkSheet = {};
  let r = 0; // current row (0-based)

  // Helper: write one row of cells
  const wr = (cells: Record<string, any>[]) => {
    cells.forEach((c, ci) => {
      ws[XLSX.utils.encode_cell({ r, c: ci })] = c;
    });
    r++;
  };

  const horizon = Math.max(1, inp.horizonYears || 15);

  // ── INPUTS SECTION ───────────────────────────────────────────────
  // Row references (0-based row numbers, will become 1-based in formulas)
  wr(sectionRow('INPUTS', 3));
  const inputStart = r; // first input row

  // Each input: [label, value, format].  We'll reference them by row.
  const inputs: [string, number | string, string][] = [
    ['Purchase Price',       inp.purchasePrice,       FMT_DOLLAR_0],  // row inputStart+0
    ['Closing Costs',        inp.closingCosts,         FMT_DOLLAR_0],
    ['Loan %',               inp.loanPercent,           FMT_PCT],
    ['Interest Rate',        inp.interestRate,          FMT_PCT],
    ['Loan Term (yrs)',      inp.loanTermYears,         FMT_INT],
    ['Loan Points',          inp.loanPoints,            FMT_PCT],
    ['Gross Annual Rent',    inp.grossAnnualRent,       FMT_DOLLAR_0],
    ['Rent Growth',          inp.rentGrowth,            FMT_PCT],
    ['Property Taxes',       inp.taxes,                 FMT_DOLLAR_0],
    ['Insurance',            inp.insurance,             FMT_DOLLAR_0],
    ['HOA',                  inp.hoa,                   FMT_DOLLAR_0],
    ['Other Expenses',       inp.otherExpenses,         FMT_DOLLAR_0],
    ['Expense Growth',       inp.expenseGrowth,         FMT_PCT],
    ['Land %',               inp.landPercent,           FMT_PCT],
    ['Horizon (yrs)',        horizon,                   FMT_INT],
    ['Appreciation',         inp.appreciation,          FMT_PCT],
    ['Selling Costs %',      inp.sellingCostsPercent,   FMT_PCT],
    ['Tax Rate',             inp.taxRate,               FMT_PCT],
    ['Cap Gains Rate',       inp.capGainsRate,          FMT_PCT],
    ['Address',              inp.address || '',         ''],
  ];

  for (const [lbl, val, fmt] of inputs) {
    wr([
      label(lbl),
      typeof val === 'number' ? inputCell(val, fmt) : cell(val, { fill: FILL_INPUT }),
      cell(fmt === FMT_PCT ? '(decimal as %)' : '', { font: { italic: true, color: { rgb: '808080' } } }),
    ]);
  }
  const inputEnd = r - 1;

  // Named cell references (1-based row)  B column = col index 1
  const R = (offset: number) => `B${inputStart + offset + 1}`;
  const purchasePrice   = R(0);
  const closingCosts    = R(1);
  const loanPct         = R(2);
  const intRate         = R(3);
  const loanTerm        = R(4);
  const loanPts         = R(5);
  const rent            = R(6);
  const rentGrowth      = R(7);
  const propTaxes       = R(8);
  const insurance       = R(9);
  const hoa             = R(10);
  const otherExp        = R(11);
  const expGrowth       = R(12);
  const landPct         = R(13);
  const horizonRef      = R(14);
  const appreciation    = R(15);
  const sellCostPct     = R(16);
  const taxRate         = R(17);
  const capGainsRate    = R(18);

  r++; // blank row

  // ── DERIVED VALUES ───────────────────────────────────────────────
  wr(sectionRow('DERIVED VALUES', 3));
  const derivedStart = r;
  const derivedRows: [string, string, string][] = [
    ['Loan Amount',              `${purchasePrice}*${loanPct}`, FMT_DOLLAR],
    ['Points Cost',              `B${r + 1}*${loanPts}`, FMT_DOLLAR],     // loanAmount * loanPoints
    ['Down Payment (Financed)',  `${purchasePrice}-B${r + 1}+${closingCosts}+B${r + 2}`, FMT_DOLLAR],
    ['Cash Outlay (Cash)',       `${purchasePrice}+${closingCosts}`, FMT_DOLLAR],
    ['Building Value',           `${purchasePrice}*(1-${landPct})`, FMT_DOLLAR],
    ['Annual Depreciation',      `B${r + 5}/27.5`, FMT_DOLLAR],
    ['Annual Points Amortization', `IF(${loanTerm}>0,B${r + 2}/${loanTerm},0)`, FMT_DOLLAR],
    ['Base Expenses',            `${propTaxes}+${insurance}+${hoa}+${otherExp}`, FMT_DOLLAR_0],
    ['Monthly Rate',             `${intRate}/12`, '0.0000%'],
    ['Num Payments',             `${loanTerm}*12`, FMT_INT],
    ['Monthly Payment',          `IF(B${r + 9}=0,IF(B${r + 10}>0,B${r + 1}/B${r + 10},0),B${r + 1}*B${r + 9}/(1-(1+B${r + 9})^(-B${r + 10})))`, FMT_DOLLAR],
  ];

  for (const [lbl, formula, fmt] of derivedRows) {
    wr([label(lbl, { fill: FILL_DERIVED }), formulaCell(formula, fmt, { fill: FILL_DERIVED }), cell('', { fill: FILL_DERIVED })]);
  }

  // Named derived cell refs
  const loanAmount   = `B${derivedStart + 1}`;
  const pointsCost   = `B${derivedStart + 2}`;
  const downPayment  = `B${derivedStart + 3}`;
  const cashOutlay   = `B${derivedStart + 4}`;
  const bldgValue    = `B${derivedStart + 5}`;
  const annDep       = `B${derivedStart + 6}`;
  const annPtsAmort  = `B${derivedStart + 7}`;
  const baseExp      = `B${derivedStart + 8}`;
  const monthlyRate  = `B${derivedStart + 9}`;
  const nPayments    = `B${derivedStart + 10}`;
  const monthlyPmt   = `B${derivedStart + 11}`;

  r++; // blank row

  // ── CASH SCENARIO ────────────────────────────────────────────────
  const cashCols = ['Year', 'Rent', 'Expenses', 'NOI', 'Depreciation', 'Taxable Income', 'Taxes', 'After-Tax CF', 'CF (No Dep)', 'Dep Tax Shield'];
  wr(sectionRow('CASH SCENARIO — YEAR BY YEAR', cashCols.length));
  const cashHdrRow = r;
  wr(cashCols.map(h => hdr(h)));
  const cashDataStart = r; // first data row

  for (let y = 1; y <= horizon; y++) {
    const row1 = cashDataStart + 1; // Excel 1-based for first data row
    const curRow = cashDataStart + y; // Excel 1-based current row
    const prevRow = curRow - 1;
    const isAlt = y % 2 === 0;
    const bg = isAlt ? { fill: FILL_ALT_ROW } : {};

    const yearF = String(y);
    const rentF = y === 1 ? rent : `B${prevRow}*(1+${rentGrowth})`;
    const expF  = y === 1 ? baseExp : `C${prevRow}*(1+${expGrowth})`;
    const noiF  = `B${curRow}-C${curRow}`;           // D = rent - expenses
    const depF  = annDep;                              // E = annual depreciation
    const taxIncF = `D${curRow}-E${curRow}`;          // F = NOI - dep
    const taxesF = `MAX(F${curRow},0)*${taxRate}`;    // G
    const atcfF = `D${curRow}-G${curRow}`;            // H = NOI - taxes
    const taxIncNoDepF = `D${curRow}`;                // taxable income without dep
    const taxesNoDepF  = `MAX(D${curRow},0)*${taxRate}`;
    const cfNoDepF = `D${curRow}-${taxesNoDepF}`;     // I = NOI - taxes(noDep)
    const shieldF = `H${curRow}-I${curRow}`;          // J

    wr([
      cell(y, bg), formulaCell(rentF, FMT_DOLLAR, bg), formulaCell(expF, FMT_DOLLAR, bg),
      formulaCell(noiF, FMT_DOLLAR, bg), formulaCell(depF, FMT_DOLLAR, bg),
      formulaCell(taxIncF, FMT_DOLLAR, bg), formulaCell(taxesF, FMT_DOLLAR, bg),
      formulaCell(atcfF, FMT_DOLLAR, bg), formulaCell(cfNoDepF, FMT_DOLLAR, bg),
      formulaCell(shieldF, FMT_DOLLAR, bg),
    ]);
  }
  const cashDataEnd = r; // one past last data row

  r++; // blank row

  // Cash IRR cash flows
  wr(sectionRow('CASH SCENARIO — CASH FLOWS & IRR', 3));
  const cashCfHdr = r;
  wr([hdr('Period'), hdr('Cash Flow'), hdr('')]);
  const cashCfDataStart = r;

  // t=0: initial outflow
  wr([cell('Initial'), formulaCell(`-(${purchasePrice}+${closingCosts})`, FMT_DOLLAR), cell('')]);

  // t=1..N: after-tax CF  (column H in cash scenario)
  for (let y = 1; y <= horizon; y++) {
    const cashRow = cashDataStart + y; // H column
    const isLast = y === horizon;
    if (!isLast) {
      wr([cell(`Year ${y}`), formulaCell(`H${cashRow}`, FMT_DOLLAR), cell('')]);
    }
  }

  // Last year + sale
  // We need sale refs — build sale section first, then come back. 
  // Instead, embed sale formulas inline.
  const finalPriceF = `${purchasePrice}*(1+${appreciation})^${horizonRef}`;
  const sellCostsF = `(${finalPriceF})*${sellCostPct}`;
  const grossSaleF = `(${finalPriceF})-(${sellCostsF})`;
  const accumDepF = `${annDep}*${horizonRef}`;
  const adjBasisF = `${purchasePrice}-(${accumDepF})`;
  const gainCashF = `(${grossSaleF})-(${adjBasisF})`;
  const recapCashF = `MIN(${accumDepF},MAX(${gainCashF},0))`;
  const capGainCashF = `MAX((${gainCashF})-(${recapCashF}),0)`;
  const recapTaxCashF = `(${recapCashF})*${taxRate}`;
  const capTaxCashF = `(${capGainCashF})*${capGainsRate}`;
  const saleNetCashF = `(${grossSaleF})-(${recapTaxCashF})-(${capTaxCashF})`;

  const lastCashYearRow = cashDataStart + horizon;
  wr([cell(`Year ${horizon} + Sale`), formulaCell(`H${lastCashYearRow}+(${saleNetCashF})`, FMT_DOLLAR), cell('')]);

  const cashCfDataEnd = r;
  // IRR formula
  const cashCfRange = `B${cashCfDataStart + 1}:B${cashCfDataEnd}`;
  wr([label('IRR'), formulaCell(`IFERROR(IRR(${cashCfRange}),"N/A")`, FMT_PCT, { font: FONT_BOLD }), cell('')]);

  // Totals
  const cashOpsRange = `H${cashDataStart + 1}:H${cashDataStart + horizon}`;
  wr([label('Operations Cash Flow'), formulaCell(`SUM(${cashOpsRange})`, FMT_DOLLAR), cell('')]);
  const cashOpsRow = r; // 1-based row number of ops CF
  wr([label('Sale Net Proceeds'), formulaCell(saleNetCashF, FMT_DOLLAR), cell('')]);
  const cashSaleRow = r; // 1-based row number of sale net
  wr([label('Total Returns'), formulaCell(`B${cashOpsRow}+B${cashSaleRow}`, FMT_DOLLAR), cell('')]);
  const cashTotalRow = r;
  wr([label('Net Profit'), formulaCell(`B${cashTotalRow}-${cashOutlay}`, FMT_DOLLAR, { font: FONT_BOLD }), cell('')]);

  r += 2; // blank rows

  // ── FINANCED SCENARIO ────────────────────────────────────────────
  const finCols = ['Year', 'Rent', 'Expenses', 'NOI', 'Depreciation', 'Interest Paid', 'Principal Paid', 'Debt Service', 'Loan Balance', 'Taxable Income', 'Taxes', 'After-Tax CF', 'CF (No Dep)', 'Dep Tax Shield'];
  wr(sectionRow('FINANCED SCENARIO — YEAR BY YEAR', finCols.length));
  wr(finCols.map(h => hdr(h)));
  const finDataStart = r;

  for (let y = 1; y <= horizon; y++) {
    const curRow = finDataStart + y; // 1-based
    const prevRow = curRow - 1;
    const isAlt = y % 2 === 0;
    const bg = isAlt ? { fill: FILL_ALT_ROW } : {};

    // A=Year B=Rent C=Expenses D=NOI E=Dep F=InterestPaid G=PrincipalPaid H=DebtService I=LoanBalance J=TaxableIncome K=Taxes L=AfterTaxCF M=CF(NoDep) N=DepShield

    const rentF = y === 1 ? rent : `B${prevRow}*(1+${rentGrowth})`;
    const expF  = y === 1 ? baseExp : `C${prevRow}*(1+${expGrowth})`;
    const noiF  = `B${curRow}-C${curRow}`;
    const depF  = annDep;

    // Interest/Principal: for simplicity we use the annual approximation via balance tracking
    // interestPaid(y) ≈ for monthly loop. Excel approach: use balance from prev year.
    // We'll use CUMIPMT and CUMPRINC which are standard Excel financial functions.
    const cumIntF = y === 1
      ? `IF(${monthlyRate}=0,0,-CUMIPMT(${monthlyRate},${nPayments},${loanAmount},1,12,0))`
      : `IF(${monthlyRate}=0,0,-CUMIPMT(${monthlyRate},${nPayments},${loanAmount},${(y-1)*12+1},${y*12},0))`;
    const cumPrinF = y === 1
      ? `IF(${monthlyRate}=0,IF(${nPayments}>0,${loanAmount}/B${derivedStart + 10}*12,0),-CUMPRINC(${monthlyRate},${nPayments},${loanAmount},1,12,0))`
      : `IF(${monthlyRate}=0,IF(${nPayments}>0,${loanAmount}/B${derivedStart + 10}*12,0),-CUMPRINC(${monthlyRate},${nPayments},${loanAmount},${(y-1)*12+1},${y*12},0))`;
    const dbtSvcF = `F${curRow}+G${curRow}`;
    const balF = y === 1
      ? `${loanAmount}-G${curRow}`
      : `I${prevRow}-G${curRow}`;

    // Taxable income (financed) = NOI - interest - pointsAmort - depreciation
    const taxIncF = `D${curRow}-F${curRow}-${annPtsAmort}-E${curRow}`;
    const taxesF  = `MAX(J${curRow},0)*${taxRate}`;
    const atcfF   = `(D${curRow}-H${curRow})-K${curRow}`;

    // No-dep version: taxable = NOI - interest - pointsAmort  (no dep)
    const taxesNoDepF = `MAX(D${curRow}-F${curRow}-${annPtsAmort},0)*${taxRate}`;
    const cfNoDepF = `(D${curRow}-H${curRow})-(${taxesNoDepF})`;
    const shieldF = `L${curRow}-M${curRow}`;

    wr([
      cell(y, bg),
      formulaCell(rentF, FMT_DOLLAR, bg), formulaCell(expF, FMT_DOLLAR, bg),
      formulaCell(noiF, FMT_DOLLAR, bg), formulaCell(depF, FMT_DOLLAR, bg),
      formulaCell(cumIntF, FMT_DOLLAR, bg), formulaCell(cumPrinF, FMT_DOLLAR, bg),
      formulaCell(dbtSvcF, FMT_DOLLAR, bg), formulaCell(balF, FMT_DOLLAR, bg),
      formulaCell(taxIncF, FMT_DOLLAR, bg), formulaCell(taxesF, FMT_DOLLAR, bg),
      formulaCell(atcfF, FMT_DOLLAR, bg), formulaCell(cfNoDepF, FMT_DOLLAR, bg),
      formulaCell(shieldF, FMT_DOLLAR, bg),
    ]);
  }
  const finDataEnd = r;

  r++; // blank row

  // Financed IRR cash flows
  wr(sectionRow('FINANCED SCENARIO — CASH FLOWS & IRR', 3));
  wr([hdr('Period'), hdr('Cash Flow'), hdr('')]);
  const finCfDataStart = r;

  // t=0: down payment
  wr([cell('Initial'), formulaCell(`-${downPayment}`, FMT_DOLLAR), cell('')]);

  for (let y = 1; y <= horizon; y++) {
    const finRow = finDataStart + y;
    const isLast = y === horizon;
    if (!isLast) {
      wr([cell(`Year ${y}`), formulaCell(`L${finRow}`, FMT_DOLLAR), cell('')]);
    }
  }

  // Last year + sale (financed)
  const lastFinBalance = `I${finDataStart + horizon}`;
  const gainFinF = `(${grossSaleF})-(${lastFinBalance})-(${adjBasisF})`;
  const recapFinF = `MIN(${accumDepF},MAX(${gainFinF},0))`;
  const capGainFinF = `MAX((${gainFinF})-(${recapFinF}),0)`;
  const recapTaxFinF = `(${recapFinF})*${taxRate}`;
  const capTaxFinF = `(${capGainFinF})*${capGainsRate}`;
  const saleNetFinF = `(${grossSaleF})-(${lastFinBalance})-(${recapTaxFinF})-(${capTaxFinF})`;

  const lastFinYearRow = finDataStart + horizon;
  wr([cell(`Year ${horizon} + Sale`), formulaCell(`L${lastFinYearRow}+(${saleNetFinF})`, FMT_DOLLAR), cell('')]);

  const finCfDataEnd = r;
  const finCfRange = `B${finCfDataStart + 1}:B${finCfDataEnd}`;
  wr([label('IRR'), formulaCell(`IFERROR(IRR(${finCfRange}),"N/A")`, FMT_PCT, { font: FONT_BOLD }), cell('')]);

  const finOpsRange = `L${finDataStart + 1}:L${finDataStart + horizon}`;
  wr([label('Operations Cash Flow'), formulaCell(`SUM(${finOpsRange})`, FMT_DOLLAR), cell('')]);
  const finOpsRow = r;
  wr([label('Sale Net Proceeds'), formulaCell(saleNetFinF, FMT_DOLLAR), cell('')]);
  const finSaleRow = r;
  wr([label('Total Returns'), formulaCell(`B${finOpsRow}+B${finSaleRow}`, FMT_DOLLAR), cell('')]);
  const finTotalRow = r;
  wr([label('Net Profit'), formulaCell(`B${finTotalRow}-${downPayment}`, FMT_DOLLAR, { font: FONT_BOLD }), cell('')]);

  r += 2;

  // ── SALE ANALYSIS ────────────────────────────────────────────────
  wr(sectionRow('SALE ANALYSIS', 3));
  wr([label('Future Property Value'), formulaCell(finalPriceF, FMT_DOLLAR), cell('')]);
  wr([label('Selling Costs'), formulaCell(sellCostsF, FMT_DOLLAR), cell('')]);
  wr([label('Gross Sale Proceeds'), formulaCell(grossSaleF, FMT_DOLLAR), cell('')]);
  wr([label('Accumulated Depreciation'), formulaCell(accumDepF, FMT_DOLLAR), cell('')]);
  wr([label('Adjusted Basis'), formulaCell(adjBasisF, FMT_DOLLAR), cell('')]);
  wr([label('Cash Sale Net'), formulaCell(saleNetCashF, FMT_DOLLAR), cell('')]);
  wr([label('Financed Sale Net'), formulaCell(saleNetFinF, FMT_DOLLAR), cell('')]);

  // Set worksheet range
  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: r - 1, c: finCols.length - 1 } });

  // Column widths
  ws['!cols'] = [
    { wch: 28 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 16 },
    { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 16 }, { wch: 16 },
    { wch: 14 }, { wch: 16 }, { wch: 16 }, { wch: 14 },
  ];

  const sheetName = sanitizeSheetName(name);
  XLSX.utils.book_append_sheet(wb, ws, sheetName);
}

/* ================================================================== */
/*  Comparison Sheet (all properties side by side — formula refs)      */
/* ================================================================== */
function buildComparisonSheet(wb: XLSX.WorkBook, properties: PropertyData[]) {
  const rows: Record<string, any>[][] = [];
  const nProps = properties.length;

  // Header row
  rows.push([label(''), ...properties.map(p => hdr(p.name))]);

  // Section: Inputs
  rows.push(sectionRowStyled('INPUTS', nProps + 1));

  const inputDefs: [string, (i: InputState) => number | string, string][] = [
    ['Purchase Price',    i => i.purchasePrice, FMT_DOLLAR_0],
    ['Closing Costs',     i => i.closingCosts, FMT_DOLLAR_0],
    ['Loan %',            i => i.loanPercent, FMT_PCT],
    ['Interest Rate',     i => i.interestRate, FMT_PCT],
    ['Loan Term (yrs)',   i => i.loanTermYears, FMT_INT],
    ['Loan Points',       i => i.loanPoints, FMT_PCT],
    ['Gross Annual Rent', i => i.grossAnnualRent, FMT_DOLLAR_0],
    ['Rent Growth',       i => i.rentGrowth, FMT_PCT],
    ['Property Taxes',    i => i.taxes, FMT_DOLLAR_0],
    ['Insurance',         i => i.insurance, FMT_DOLLAR_0],
    ['HOA',               i => i.hoa, FMT_DOLLAR_0],
    ['Other Expenses',    i => i.otherExpenses, FMT_DOLLAR_0],
    ['Expense Growth',    i => i.expenseGrowth, FMT_PCT],
    ['Land %',            i => i.landPercent, FMT_PCT],
    ['Horizon (yrs)',     i => i.horizonYears, FMT_INT],
    ['Appreciation',      i => i.appreciation, FMT_PCT],
    ['Selling Costs %',   i => i.sellingCostsPercent, FMT_PCT],
    ['Tax Rate',          i => i.taxRate, FMT_PCT],
    ['Cap Gains Rate',    i => i.capGainsRate, FMT_PCT],
  ];

  for (const [lbl, getter, fmt] of inputDefs) {
    const row: Record<string, any>[] = [label(lbl)];
    for (const p of properties) {
      const v = getter(p.inputs);
      row.push(typeof v === 'number' ? inputCell(v, fmt) : cell(v, { fill: FILL_INPUT }));
    }
    rows.push(row);
  }

  // Section: Key Results (formulas referencing per-property sheets)
  rows.push([cell('')]);
  rows.push(sectionRowStyled('KEY RESULTS (from property sheets)', nProps + 1));

  // For each property, reference their sheet's IRR / net profit cells
  // Since sheet cell locations vary by horizon length, we use computed values for comparison.
  // The individual sheets have all the live formulas.

  const resultDefs: [string, (a: any) => number | string, string][] = [
    ['Cash Outlay (Cash)',     a => a.cash.cashOutlay, FMT_DOLLAR],
    ['IRR (Cash)',             a => a.cash.irr ?? 'N/A', FMT_PCT],
    ['Net Profit (Cash)',      a => a.cash.netProfit, FMT_DOLLAR],
    ['Total Returns (Cash)',   a => a.cash.totalWealth, FMT_DOLLAR],
    ['Cash Outlay (Financed)', a => a.financed.cashOutlay, FMT_DOLLAR],
    ['IRR (Financed)',         a => a.financed.irr ?? 'N/A', FMT_PCT],
    ['Net Profit (Financed)',  a => a.financed.netProfit, FMT_DOLLAR],
    ['Total Returns (Financed)', a => a.financed.totalWealth, FMT_DOLLAR],
  ];

  const analyses = properties.map(p => computeAnalysis(p.inputs));
  for (const [lbl, getter, fmt] of resultDefs) {
    const row: Record<string, any>[] = [label(lbl)];
    for (const a of analyses) {
      const v = getter(a);
      if (typeof v === 'number') {
        row.push(cell(v, { numFmt: fmt, font: FONT_BOLD }));
      } else {
        row.push(cell(v, { font: FONT_BOLD }));
      }
    }
    rows.push(row);
  }

  // Build worksheet from rows
  const ws: XLSX.WorkSheet = {};
  rows.forEach((row, ri) => {
    row.forEach((c, ci) => {
      ws[XLSX.utils.encode_cell({ r: ri, c: ci })] = c;
    });
  });
  ws['!ref'] = XLSX.utils.encode_range({ s: { r: 0, c: 0 }, e: { r: rows.length - 1, c: nProps } });
  ws['!cols'] = [{ wch: 28 }, ...properties.map(() => ({ wch: 20 }))];

  XLSX.utils.book_append_sheet(wb, ws, 'Comparison');
}

function sectionRowStyled(text: string, cols: number): Record<string, any>[] {
  const row: Record<string, any>[] = [cell(text, { font: FONT_SECTION, fill: FILL_SECTION })];
  for (let i = 1; i < cols; i++) row.push(cell('', { fill: FILL_SECTION }));
  return row;
}

/* ------------------------------------------------------------------ */
/*  Helpers                                                            */
/* ------------------------------------------------------------------ */
function sanitizeSheetName(name: string): string {
  return name.replace(/[[\]*?/\\:]/g, '').substring(0, 31) || 'Property';
}
